# NUC900 series audio

snd-soc-nuc900-ac97-objs := nuc900-ac97.o
snd-soc-nuc900-i2s-objs := nuc900-i2s.o
snd-soc-nuc900-pcm-objs := nuc900-pcm.o

obj-$(CONFIG_SND_SOC_NUC900) += snd-soc-nuc900-pcm.o
obj-$(CONFIG_SND_SOC_NUC900EVB_AC97) += snd-soc-nuc900-ac97.o
obj-$(CONFIG_SND_SOC_NUC900EVB_I2S) += snd-soc-nuc900-i2s.o

# Boards
snd-soc-nuc900-audio-objs := nuc900-audio.o
obj-$(CONFIG_SND_SOC_NUC900) += snd-soc-nuc900-audio.o